# Generated by Django 4.2 on 2025-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='street_number',
            field=models.IntegerField(default=0),
        ),
    ]
