# Generated by Django 4.2 on 2025-01-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
